spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/polling_publisher
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  actuator:
    health:
      kafka:
        enabled: true
      db:
        enabled: true
